name: gaussian_splatting
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

resolution: workspace

environment:
  sdk: ^3.8.1

dependencies:
  community_charts_flutter: ^1.0.4
  device_frame: ^1.4.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_gaussian_splatter: ^0.3.0
  flutter_hooks: ^0.21.2
  graphite: ^1.2.1
  heroine: ^0.5.0-dev.7
  hooks_riverpod: ^2.6.1
  motor: ^1.0.0-dev.9
  rivership: ^0.3.0-dev.12
  stupid_simple_sheet: ^0.3.0+1
  three_js: ^0.2.4
  three_js_transform_controls: ^0.2.0
  value_notifier_tools: ^0.1.2
  wnma_talk:
    path: ../../packages/wnma_talk

dev_dependencies:
  flutter_test:
    sdk: flutter
  lintervention: ^0.3.1

flutter:
  uses-material-design: true

  assets:
    - assets/
