name: physical_ui
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0
resolution: workspace

environment:
  sdk: ^3.8.1

dependencies:
  device_frame: ^1.4.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_hooks: ^0.21.2
  halofoil: ^0.0.1
  heroine: ^0.5.0-dev.7
  hooks_riverpod: ^2.6.1
  liquid_glass_renderer: 
    git: 
      url: https://github.com/whynotmake-it/flutter_liquid_glass
      path: packages/liquid_glass_renderer
      ref: f77f38835524f3a4fbec2d093b794c3c545aaeab
  motor: ^1.0.0-dev.9
  rivership: ^0.3.0-dev.12
  stupid_simple_sheet: ^0.3.0+1
  value_notifier_tools: ^0.1.2
  wnma_talk:
    path: ../../packages/wnma_talk

dev_dependencies:
  flutter_test:
    sdk: flutter
  lintervention: ^0.3.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/history/

  fonts:
    - family: Archivo
      fonts:
        - asset: assets/Archivo-VariableFont_wdth,wght.ttf
