name: physical_ui
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0
resolution: workspace

environment:
  sdk: ^3.8.1

dependencies:
  device_frame: ^1.4.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_hooks: ^0.21.2
  heroine: ^0.5.0-dev.7
  liquid_glass_renderer: ^0.1.1-dev.10
  hooks_riverpod: ^2.6.1
  motor: ^1.0.0-dev.9
  motor_example:
    git:
      url: https://github.com/whynotmake-it/rivership
      ref: vibe-phases
      path: packages/motor/example
  rivership: ^0.3.0-dev.7
  stupid_simple_sheet: ^0.0.3+1
  value_notifier_tools: ^0.1.2
  wnma_talk:
    path: ../../packages/wnma_talk

dependency_overrides:
  motor:
    git:
      url: https://github.com/whynotmake-it/rivership
      ref: vibe-phases
      path: packages/motor
  stupid_simple_sheet:  
    git:
      url: https://github.com/whynotmake-it/rivership
      ref: vibe-phases
      path: packages/stupid_simple_sheet

dev_dependencies:
  flutter_test:
    sdk: flutter
  lintervention: ^0.3.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/history/

  fonts:
    - family: Archivo
      fonts:
        - asset: assets/Archivo-VariableFont_wdth,wght.ttf
