name: physical_ui
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  heroine: ^0.5.0-dev.7
  motor: ^1.0.0-dev.4
  wnma_talk:
    path: /Users/tim/Developer/talks/packages/wnma_talk

dev_dependencies:
  flutter_test:
    sdk: flutter
  lintervention: ^0.3.1

flutter:
  uses-material-design: true
