name: wnma_talk
description: Shared resources for flutter slides
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flex_seed_scheme: ^3.5.1
  flutter:
    sdk: flutter
  flutter_deck:
    git:
      url: git@github.com:timcreatedit/flutter_deck.git
      ref: feat/navigator-observers
      path: packages/flutter_deck
  flutter_hooks: ^0.21.3+1
  rivership: ^0.3.0-dev.7
  video_player: ^2.10.0
  wnmi_design:
    path: /Users/tim/Developer/talks/packages/wnmi_design

dev_dependencies:
  flutter_test:
    sdk: flutter
  lintervention: ^0.3.1
  mocktail: ^1.0.3
