name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  semantic_pull_request:
    name: Check PR Title
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  flutter-check:
    name: Build Check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: 📚 Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      
      - name: 🐦 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      
      - name: Ⓜ️ Set up Melos
        uses: bluefireteam/melos-action@v3

      - name: 🧪 Run Analyze
        run: melos run analyze

      - name: 📝 Run Test
        run: melos run coverage

      - name: 📊 Generate Coverage
        id: coverage-report
        uses: whynotmake-it/dart-coverage-assistant@v1.1
        with:
          generate_badges: pr
      
  
  check_generation:
    name: Check Code Generation
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: 📚 Checkout
        uses: actions/checkout@v6

      - name: 🐦 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Ⓜ️ Set up Melos
        uses: bluefireteam/melos-action@v3

      - name: 🔨 Generate
        run: melos run generate

      - name: 🔎 Check there are no uncommitted changes
        run: git add . && git diff --cached --exit-code
  